---
- name: Change grub defaults
  hosts: all

  tasks:
    - name: Check if options in GRUB_CMDLINE_LINUX  are present
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX=".* net\.ifnames=0 biosdevname=0'
        state: absent
      check_mode: true
      register: grub_cmdline_check
      changed_when: false
    - name: Add options if they did not present
      lineinfile:
        path: /etc/default/grub
        regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
        backrefs: yes
        line: '\1 net.ifnames=0 biosdevname=0"'
      when: grub_cmdline_check.found == 0
      notify: update_grub
  handlers:
    - name: update_grub
      command:
        cmd: grub2-mkconfig
...